# Trackr configuration

[global]
geo_ip_database = "./var/dbip-country-lite.mmdb"

# Global tags can be specified here in key="value" format.
[global.tags]
  dc = "eu-west-1" # will tag all metrics with dc=us-east-1
  ## Environment variables can be used as tags, and throughout the config file
  user = "$USER"

[[trackers]]
origin = "http://localhost:8000"
tracking_id = "UA-XXXX-Y"

[[outputs.file]]
  ## Files to write to, "stdout" is a specially handled file.
  files = ["stdout"]
  ## Data format to output.
  #data_format = "template"
  data_format = "json"

# [[outputs.prometheus]]
#   ## Address to listen on
#   listen = ":9213"
#   ## Path to publish the metrics on.
#   path = "/metrics"
#   ## Expiration interval for each metric. 0 == no expiration
#   # expiration_interval = "60s"

[[outputs.loki]]
  ## Loki URL
  url = "http://localhost:3100"
  ## Timeout
  timeout = "2s"
  ## Batch size
  batch_size = 10
  ## Batch interval
  batch_interval = "10s"
  data_format = "template"
